name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: cache plugins
        uses: actions/cache@v4
        with:
          key: plugin-cache-${{ runner.os }}-${{ hashFiles('**/plugins.lock.json') }}
          path: ${{ env.PLUGIN_SDK_CACHE }}
          restore-keys: |
            plugin-cache-${{ runner.os }}-

      - name: restore
        run: dotnet restore --locked-mode

      # Ensure .csproj file exists
      - name: check .csproj file
        run: |
          if [ ! -f "src/src/LethalCompany.Doom.csproj" ]; then
            echo "ERROR: .csproj file not found!"
            exit 1
          fi

      # Run dotnet publish in verbose mode to capture detailed logs
      - name: publish project
        run: |
          echo "Running dotnet publish in verbose mode..."
          dotnet publish src/src/LethalCompany.Doom.csproj -c Release -o ${{ github.workspace }}/.package --no-restore -v diag

      # List the output directory contents after publish to confirm files are there
      - name: list package directory
        run: ls -al ${{ github.workspace }}/.package

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lc-doom
          path: ${{ github.workspace }}/.package
