name: Build LC-Doom Mod

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.101
          cache: true
          cache-dependency-path: src/src/packages.lock.json
          global-json-file: global.json

      - name: Restore Dependencies for LethalCompany.Doom
        run: dotnet restore src/src/LethalCompany.Doom.csproj

      - name: Build LethalCompany.Doom
        run: dotnet build src/src/LethalCompany.Doom.csproj -c Release

      - name: Publish LethalCompany.Doom
        run: dotnet publish src/src/LethalCompany.Doom.csproj -c Release -o .package --no-restore

      - name: Restore Dependencies for ManagedDoom
        run: dotnet restore src/src/LethalCompany.Doom.ManagedDoom.csproj  # Updated path for ManagedDoom

      - name: Build ManagedDoom
        run: dotnet build src/src/LethalCompany.Doom.ManagedDoom.csproj -c Release  # Updated path for ManagedDoom

      - name: Publish ManagedDoom
        run: dotnet publish src/src/LethalCompany.Doom.ManagedDoom.csproj -c Release -o .package --no-restore  # Updated path for ManagedDoom

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lc-doom
          path: .package/**  # Upload all files from the .package directory
