name: Build LC-Doom Mod

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.101
          cache: true
          global-json-file: global.json

      - name: Restore Dependencies
        run: dotnet restore src/src/LethalCompany.Doom.csproj

      - name: Build Mod
        run: dotnet build src/src/LethalCompany.Doom.csproj -c Release

      - name: Publish Mod
        run: dotnet publish src/src/LethalCompany.Doom.csproj -c Release --no-restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lc-doom
          path: '**/*.dll'  # Adjust this to include any specific output files you want
