name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      # Upgrade cache action to v4 for Node.js 20 compatibility
      - name: cache plugins
        uses: actions/cache@v4
        with:
          key: plugin-cache-${{ runner.os }}-${{ hashFiles('**/plugins.lock.json') }}
          path: ${{ env.PLUGIN_SDK_CACHE }}
          restore-keys: |
            plugin-cache-${{ runner.os }}-

      - name: restore
        run: dotnet restore --locked-mode

      - name: publish
        run: dotnet publish src/src/LethalCompany.Doom.csproj -c Release -o ${{ github.workspace }}/.package --no-restore

      # Add this step to check the output directory
      - name: list package directory
        run: ls -al ${{ github.workspace }}/.package

      # Upgrade upload-artifact action to v5 for Node.js 20 compatibility
      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: lc-doom
          path: ${{ github.workspace }}/.package
