name: default

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  PLUGIN_SDK_CACHE: ${{ github.workspace }}/.plugins/cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.101  # Specify the exact .NET version
          cache: true
          cache-dependency-path: ./**/packages.lock.json
          global-json-file: global.json

      - name: cache plugins
        uses: actions/cache@v3
        with:
          key: plugin-cache-${{ runner.os }}-${{ hashFiles('**/plugins.lock.json') }}
          path: ${{ env.PLUGIN_SDK_CACHE }}
          restore-keys: |
            plugin-cache-${{ runner.os }}-

      - name: restore
        run: dotnet restore --locked-mode

      - name: publish
        run: dotnet publish src/src/LethalCompany.Doom.csproj -c Release --no-restore

      - name: List output directory
        run: ls -la bin/Release/netstandard2.1  # List the output files

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lc-doom
          path: bin/Release/netstandard2.1/**  # Upload all files from the output directory
